# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Programs/vivado/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/mydivu/mydivu.xci
# IP: The module: 'mydivu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/vivado/CPU_CDE_SRAM/mycpu_prj1.gen/sources_1/ip/mydivu/mydivu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mydivu'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Programs/vivado/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/mydivu/mydivu.xci
# IP: The module: 'mydivu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/vivado/CPU_CDE_SRAM/mycpu_prj1.gen/sources_1/ip/mydivu/mydivu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mydivu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
